apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      serviceAccountName: server
      containers:
        - name: hello-go
          image: danilokoda/hello-go:v5.7
          resources:
            requests:
              memory: "20Mi"
              cpu: "0.05"
            limits:
              memory: "25Mi"
              cpu: "0.05"
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            periodSeconds: 5
#            failureThreshold: 1
#            timeoutSeconds: 1
#            successThreshold: 1
#            initialDelaySeconds: 1
#          readinessProbe:
#            httpGet:
#              path: /ready
#              port: 8080
#            periodSeconds: 5
#            failureThreshold: 1
#            timeoutSeconds: 1
#            successThreshold: 1
#            initialDelaySeconds: 1
          volumeMounts:
            - mountPath: /go/myfamily
              name: config
              readOnly: true
            - mountPath: /go/mydata
              name: hello-go-volume
          envFrom:
            - secretRef:
                name: hello-go-secret
      volumes:
        - name: hello-go-volume
          persistentVolumeClaim:
            claimName: hello-go-pvc
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: family.txt